name: Generate Transcript

on:
  workflow_dispatch:
    inputs:
      record_id:
        description: "Airtable student record ID (e.g., recXXXXXX)"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          RECORD_ID: ${{ github.event.inputs.record_id }}
        run: |
          python main.py
