name: Generate Transcript

on:
  workflow_dispatch:
    inputs:
      record_id:
        description: "Airtable student record ID (e.g., recXXXXXX)"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          RECORD_ID: ${{ github.event.inputs.record_id }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          TRANSCRIPT_TABLE: ${{ secrets.TRANSCRIPT_TABLE }}   # e.g. "Students 1221"
          SCHOOL_NAME: ${{ secrets.SCHOOL_NAME }}             # e.g. "Cornerstone Education Management Organization"
          LOGO_PATH: logo_cornerstone.png                     # file in repo root (or set as a secret/var)
        run: |
          python main.py

      - name: List output directory (debug)
        run: |
          echo "Root:"
          ls -la || true
          echo "Output:"
          ls -la output || true

      - name: Upload transcript artifact
        uses: actions/upload-artifact@v4
        with:
          name: transcript
          path: output/*.pdf
          if-no-files-found: error
